alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
functions:
  - github:
      branch: main
      deploy_on_push: true
      repo: HolgerKurtz/seo-api
    name: seo-api
    routes:
      - path: /
    source_dir: /
name: seo
